<!DOCTYPE html>
<html>
<head>
	<title>EcoGeneral Loan Services | About Us</title><head>
	<link rel="stylesheet" href="static/js/jquery-ui/jquery-ui.css">
	<link rel="stylesheet" href="static/css/bootstrap/css/bootstrap-theme.css">
	<link rel="stylesheet" href="static/css/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="static/css/aboutus.css">
	<link rel="stylesheet" type="text/css" href="static/css/font-awesome/css/font-awesome.css">
	<link rel="stylesheet" href="static/css/reset.css"> <!-- CSS reset -->
	<link rel="stylesheet" href="static/css/style.css"> <!-- Resource style -->
	<link rel="stylesheet" type="text/css" href="static/css/animate.css">
	<script src="static/js/modernizr.js"></script>
</head>
<body>
	<div class="main_body clearfix">
		<div class="first_section">
			<div class="header">
				<div class="header_content">
					<div class="tabs">
						<ul>
							<li><a href="/">Home</a></li>
							<li style="background-color:#15A7DF;"><a href="/about">About</a></li>
							<li><a href="/faq">FAQ</a></li>
							<li><a href="/client">Client Zone</a></li>
						</ul>
					</div>
					<div class="social_media">
						<ul>
							<li><a href="http://facebook.com"><i class="fa fa-facebook-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="http://twitter.com"><i class="fa fa-twitter-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="http://instagram.com"><i class="fa fa-instagram font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="http://youtube.com"><i class="fa fa-youtube-play font_awesome" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="logo_wrap clearfix">
				<div class="logo_div clearfix">
					<a href="" class="clearfix">
						<div class="logo"></div>
					</a>
				</div>
				<div class="logo_content_div">
					<h1>
		                NIGERIA'S LEADING NAME IN ONLINE, PAYDAY LOANS. FOR FAST, PAPERLESS CASH
		                LOANS UNTIL PAYDAY!
					</h1>
					<span class="style">
						You can apply from <span class="white">NGN1000</span> up to <span class="white">NGN3000</span> <br> <span style="font-size:20px; color:#fff;">SAME DAY. PAY DAY. EVERYDAY.</span>
					</span>
				</div>
			</div>
		</div>

		<div class="second_section clearfix">
			<h1>About Us</h1>
			<table>
				<tbody>
					<tr>
						<td style="width:50%;">
							<span class="first_td_span">Why are we here?</span>
							<p>
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
								quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							</p>
							<p>
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
								quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							</p>
							<p>
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
								quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							</p>
							<p>
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
								quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							</p>
						</td>
						<td style="width:4%;">
							&nbsp;
						</td>
						<td style="width:46%;">
							<h1>Our Promise</h1>
							<ul>
								<li>We will always deliver a high standard of service</li>
								<li>We will be fair and transparent in our business practices</li>
								<li>We will continuously develop and improve our model so that South Africans can access short-term credit for their everyday needs.</li>
								<li>We will always reinvest in our company to ensure growth and best returns for all our clients.</li>
								<li>We will always strive to champion the customer experience</li>
							</ul>
						</td>
					</tr>
				</tbody>
			</table>
			<table class="second_section_last_table">
				<h2>Apply for an instant loan in three easy steps</h2>
				<tr>
					<td>
						<div class="digit">
							1
						</div>
						<div class="h2_p_wrap">
							<P>
								Use our sliders to indicate how much money you would like to borrrow and when your next payday is. 
								<br/><br/>
								You should always remember to borrow only what you can afford to pay back. Once you have finished the selection, hit the GET CASH button
							</P>
						</div> 
					</td>
					<td>
						<div class="digit">
							2
						</div>
						<div class="h2_p_wrap">
							<P>
								Complete your application by providing us with your personal information. We use this to assess your creditworthiness and your ability to repay the loan. 
								<br/><br/>
								Once submitted, sit back and relax while you wait for the outcome.
							</P>
						</div>
					</td>
					<td>
						<div class="digit">
							3
						</div>
						<div class="h2_p_wrap">
							<P>
								Once you have been approved, we will complete our last verification checks. If all goes well, we aim to have the money in your bank account within an hour. 
								<br/><br/>
								Remember that you can use the cash any way you want, and when you pay us back, you will immediately qualify for further finance
							</P>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<footer>
		<div class="footer">
			<div class="section_one">
				<div class="content">
					<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="aboutus.html">Aboutus</a></li>
						<li><a href="faq.html">Faqs</a></li>
						<li><a href="contactus.html">Contactus</a></li>
						<li><a href="">Policy Privacy</a></li>
						<li><a href="">Terms and Conditions</a></li>
						<li><a href="client_zone.html">Clients Zone</a></li>
					</ul>
				</div>
			</div>
			<div class="section_two">
				<div class="footer_sub">
					<strong>Fast Loans</strong>
					<span><a href="fast_loan.html">fast loans</a></span>
					<span><a href="payday_loan.html">payday loans</a></span>
				</div>
				<div class="footer_sub">
					<strong>Cash Loans</strong>
					<span><a href="easy_loan.html">easy loans</a></span>
					<span><a href="short_loan.html">short terms loan</a></span>
				</div>
				<div class="footer_sub">
					<strong>Personal Loans</strong>
					<span><a href="what_loan.html">what is a loan</a></span>
					<span><a href="online_loan.html">online loan</a></span>
				</div>
			</div>
			<div class="section_three">
				<div class="content">
					<span>Copyright &copy; Eco General 2016, <a href="http://www.effluxcompany.com/" target="_blank">powered by Efflux</a></span>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>