<!DOCTYPE html>
<html>
<head>
	<title>EcoGeneral - FAQs</title><head>
	<link rel="stylesheet" href="/static/js/jquery-ui/jquery-ui.css">
	<link rel="stylesheet" href="/static/css/bootstrap/css/bootstrap-theme.css">
	<link rel="stylesheet" href="/static/css/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/faq.css">
	<link rel="stylesheet" type="text/css" href="/static/css/font-awesome/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/reset.css"> <!-- CSS reset -->
	<link rel="stylesheet" href="/static/css/style.css"> <!-- Resource style -->
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<script src="/static/js/modernizr.js"></script>
</head>
<body>
	<div class="main_body clearfix">
		<div class="first_section">
			<div class="header">
				<div class="header_content">
					<div class="tabs">
						<ul>
							<li><a href="/">Home</a></li>
							<li><a href="/about">About</a></li>
							<li style="background-color:#15A7DF;"><a href="/faq">FAQ</a></li>
							<li><a href="/client">Client Zone</a></li>
						</ul>
					</div>
					<div class="social_media">
						<ul>
							<li><a href="http://facebook.com"><i class="fa fa-facebook-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="http://twitter.com"><i class="fa fa-twitter-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="http://instagram.com"><i class="fa fa-instagram font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="http://youtube.com"><i class="fa fa-youtube-play font_awesome" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="logo_wrap clearfix">
				<div class="logo_div clearfix">
					<a href="" class="clearfix">
						<div class="logo"></div>
					</a>
				</div>
				<div class="logo_content_div">
					<h1>
		                NIGERIA'S LEADING NAME IN ONLINE, PAYDAY LOANS. FOR FAST, PAPERLESS CASH
		                LOANS UNTIL PAYDAY!
					</h1>
					<span class="style">
						You can apply from <span class="white">NGN1000</span> up to <span class="white">NGN3000</span> <br> <span style="font-size:20px; color:#fff;">SAME DAY. PAY DAY. EVERYDAY.</span>
					</span>
				</div>
			</div>
		</div>

		<div class="second_section clearfix">
			<h1>Frequently Asked Questions</h1>
			<h2>Most popular questions</h2>
			<div class="panel-group" id="accordion">
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-1" data-toggle="collapse" data-parent="#accordion">
								I dont trust applying online. Is it safe to apply on Eco General website and is my information safe?	
							</a>
						</div>
						<div id="collapse-1" class="panel-collapse collapse">
							<div class="panel-body">
								<p>We use bank-level security technology and protocols! Rest assured that your personal information is protected through our advanced online privacy technology, Thawte SSL Extended Validation Security Certificate. This is the most powerful online security certificate currently available. You will notice a green security lock in your browser bar and a Thawte trust seal at the bottom of our website. These features indicate the level of security we have implemented to protect your personal information.</p> 
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-2" data-toggle="collapse" data-parent="#accordion">
								Can the loan be paid off early?	
							</a>
						</div>
						<div id="collapse-2" class="panel-collapse collapse">
							<div class="panel-body">
								<p>
									Yes, we actually encourage it. Unlike many other lenders, we do not penalise you for settling the loan early. The major advantage for early settlement is that you will save money on the interest you have to pay back. We calculate interest daily, therefore you only pay for the amount of days you've had the loan. All you have to do is contact our Customer service department and request an early settlement figure and they will be happy to assist you.
								</p>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-3" data-toggle="collapse" data-parent="#accordion">
								How does the interest and fees work?	
							</a>
						</div>
						<div id="collapse-3" class="panel-collapse collapse">
							<div class="panel-body">
								This largely depends on how much cash you want to borrow and how long you need it for. We calculate the interest daily and the admin fees are calculated as stipulated by the National Credit Act of 2005 for loans which fall under the "short-term transactions" category. We charge a daily interest of 0.17% which is capped at 5% per month. Our sliders will give you an exact breakdown as to how much you will need to pay back.
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-4" data-toggle="collapse" data-parent="#accordion">
								How long does it takes to get my loan?
							</a>
						</div>
						<div id="collapse-4" class="panel-collapse collapse">
							<div class="panel-body">
								If you apply on a weekday we aim for payout the same day your loan is approved. In very few instances it may take a bit longer, depending on how long the post-approval verification checks take. If everything goes according to plan, you should have the cash in your bank account within an hour of your loan being approved. If you apply over the weekend and your loan is approved, you will receive your cash on the next working day.
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-5" data-toggle="collapse" data-parent="#accordion">
								How much cash can i apply for?	
							</a>
						</div>
						<div id="collapse-5" class="panel-collapse collapse">
							<div class="panel-body">
								First time customers can apply for a loan between NGN1000 - NGN3000
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-6" data-toggle="collapse" data-parent="#accordion">
								If am blacklisted can i still apply for a loan?	
							</a>
						</div>
						<div id="collapse-6" class="panel-collapse collapse">
							<div class="panel-body">
								Yes you can! Although we conduct a full credit assessment, in some instances we will approve applications where the applicant has defaults, judgements or is a registered slow payer. As long as you meet our personal loan criteria you can apply to us for a loan of up to R3 000 and we will see if we can assist you.
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-7" data-toggle="collapse" data-parent="#accordion">
								Can i take out more than one loan?	
							</a>
						</div>
						<div id="collapse-7" class="panel-collapse collapse">
							<div class="panel-body">
								We can only give you one loan at a time, therefore you will have to repay your existing loan before we can give you another. We adhere to a strict Responsible Lending Practice which is a basic guideline as to how we combat overindebtedness and reckless lending. We advise you to only borrow what you can afford to pay back. Our short-term solutions are not intended to meet your long-term financial needs.
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-8" data-toggle="collapse" data-parent="#accordion">
								Will Eco General ask me for any documents if am approved?	
							</a>
						</div>
						<div id="collapse-8" class="panel-collapse collapse">
							<div class="panel-body">
								No, not at all! Our system is fully automated and is designed to conduct the necessary checks to approve a loan. Therefore we do not require any documents and never will. That's a promise.
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-9" data-toggle="collapse" data-parent="#accordion">
								What's the loan application process	?	
							</a>
						</div>
						<div id="collapse-9" class="panel-collapse collapse">
							<div class="panel-body">
								That's simple. You use our online sliders to tell us how much money you would like to borrow and when your next salary date is. Complete our short three-minute application form by telling us a little about yourself. We then conduct the necessary assessments and checks and provide you with the outcome within minutes. Once approved, sit back and relax while we finalise your application for payout
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default panel_border">
					<div class="panel-heading panel_heading">
						<div class="panel-title">
							<a href="#collapse-10" data-toggle="collapse" data-parent="#accordion">
								Does Eco General performs any checks after i have been approved?	
							</a>
						</div>
						<div id="collapse-10" class="panel-collapse collapse">
							<div class="panel-body">
								Yes, we perform three basic post-approval checks: bank account verification, employment and customer satisfaction checks. The bank account verification allows us to check whether you are the holder of the bank account you have provided. We conduct a short employment check to establish that you are currently working. Don't worry, we won't inform anyone you work with that you are lending money. Lastly, our payouts team will give you a ring to say hi and make sure that you are happy with our services thus far.
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<footer>
		<div class="footer">
			<div class="section_one">
				<div class="content">
					<ul>
						<li><a href="">Home</a></li>
						<li><a href="">Aboutus</a></li>
						<li><a href="">Faqs</a></li>
						<li><a href="">Contactus</a></li>
						<li><a href="">Policy Privacy</a></li>
						<li><a href="">Terms and Conditions</a></li>
						<li><a href="">Clients Zone</a></li>
					</ul>
				</div>
			</div>
			<div class="section_two">
				<div class="footer_sub">
					<strong>Fast Loans</strong>
					<span><a href="">fast loans</a></span>
					<span><a href="">payday loans</a></span>
				</div>
				<div class="footer_sub">
					<strong>Cash Loans</strong>
					<span><a href="">easy loans</a></span>
					<span><a href="">short terms loan</a></span>
				</div>
				<div class="footer_sub">
					<strong>Personal Loans</strong>
					<span><a href="">what is a loan</a></span>
					<span><a href="">online loan</a></span>
				</div>
			</div>
			<div class="section_three">
				<div class="content">
					<span>Copyright &copy; Eco General 2016, <a href="">powered by Efflux</a></span>
				</div>
			</div>
		</div>
	</footer>

	<script src="/static/js/jquery.js"></script>
	<script src="/static/css/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>