<!DOCTYPE html>
<html>
	<head>
		<title>Fast Loans</title>
		<link rel="stylesheet" href="js/jquery-ui/jquery-ui.css">
		<link rel="stylesheet" href="css/bootstrap/css/bootstrap-theme.css">
		<link rel="stylesheet" href="css/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/fast_loan.css">
		<link rel="stylesheet" type="text/css" href="css/font-awesome/css/font-awesome.css">
		<link rel="stylesheet" href="css/reset.css"> <!-- CSS reset -->
		<link rel="stylesheet" href="css/style.css"> <!-- Resource style -->
		<link rel="stylesheet" type="text/css" href="css/animate.css">
		<script src="js/modernizr.js"></script>
	</head>
	<body>
		<div class="first_section">
			<div class="header">
				<div class="header_content">
					<div class="tabs">
						<ul>
							<li style="background-color:#15A7DF;"><a href="/">Home</a></li>
							<li><a href="/about">About</a></li>
							<li><a href="/faq">FAQ</a></li>
							<li><a href="/client">Client Zone</a></li>
						</ul>
					</div>
					<div class="social_media">
						<ul>
							<li><a href="www.facebook.com"><i class="fa fa-facebook-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="wwww.twitter.com"><i class="fa fa-twitter-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="www.instagram.com"><i class="fa fa-instagram font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="www.youtube.com"><i class="fa fa-youtube-play font_awesome" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="logo_wrap class="clearfix">
				<div class="logo_div class="clearfix">
					<a href="" class="clearfix">
						<div class="logo"></div>
					</a>
				</div>
				<div class="logo_content_div">
					<h1>
		                NIGERIA'S LEADING NAME IN ONLINE, PAYDAY LOANS. FOR FAST, PAPERLESS CASH
		                LOANS UNTIL PAYDAY!
					</h1>
					<span class="style">
						You can apply from <span class="white">NGN1000</span> up to <span class="white">NGN3000</span> <br> <span style="font-size:20px; color:#fff;">SAME DAY. PAY DAY. EVERYDAY.</span>
					</span>
				</div>
			</div>
		</div>
		<div class="second_section clearfix">
			<h1>Fast Loans</h1>
			<em>
				Author: <b>Panama Palane</b> <br>
				Date: June 6, 2016
			</em>
			<br>
			<br>
			<h2>
				Advantages and potential pitfalls of fast loans
			</h2>
			<p>
				There are some obvious reasons why we often need quick cash loans in order to meet our short-term (yet urgent) financial requirements. There could be a sudden emergency or an unexpected expense. Whatever the case, a fast loan always presents its advantages when needed. <br><br> 

				Fast loans are highly sought after because they are quick. Unlike applying for a traditional loan with your local bank or other lenders, with a fast loan you receive a response by the end of the day. With most traditional lenders, it can take up to one week to receive an approval or denial for a loan. There are many individuals who cannot wait that long. <br><br>

				What also makes fast loans attractive is that they offer easy qualifying criteria, a simple application process, fast approval, no credit checks, and not much paperwork. <br> <br>

				You can apply for a fast loan without having to visit the lender branch where you may go through piles of complicated paperwork. <br><br>

				A good thing about fast loans is that almost anyone can qualify for it, as long as you're over 18 and employed with an active bank account in your name. You can get the borrowed money paid into your bank account within hours. <br><br>

				What's more, even if you fail to make the repayment on the due date, fast loan lenders often allow extra time to pay off the debt. Another popular advantage is that many lending establishments do not run credit checks. This means that even if you have bad credit, you may likely obtain a fast loan. Instead of checking your credit, the lender may decide to examine when your next paycheck will arrive. So far, a fast loan sounds good doesn't it? Unfortunately, not everything that glitters is gold. Like most things in life, fast loans have their disadvantages and potential pitfalls, and as a borrower, you should know about them. <br><br>

				The biggest disadvantage of a fast loan is the amount of interest charged. Each lender is likely to charge different interest rates, which may be sky high, unlike the interest rates charged by most banks. <br><br>

				If you must obtain a fast cash loan, it's important to make sure that you'll be able to repay the loan in the appropriate amount of time. This is because late fees charged on fast loans can be high. Therefore, you need to make sure that you choose the right lender. Which is why wanna loan? is here to create the right solution for you. <br><br>

				As one of South Africa's most reliable and trusted fast loan lenders, wanna loan? has been helping South Africans across the country make ends meet until payday. As a uniquely South African company, we are committed to responsible lending and advise to only borrow as much as you can afford to pay back. <br><br>

				EcoGeneral fast, paperless cash loans until payday.
			</p>
		</div>
	</body>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  	<div class="modal-dialog" role="document">
		    <div class="modal-content">
		        <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel" style="font-weight: 600; font-size: 20px; font-family: 'Montserrat', sans-serif; color: #272968;">Contact Us</h4>
		        </div>
		      	<div class="modal-body">
			        <p>
			        	If you need to contact us for any reason regarding your loan; want to know more about our company, products or services; have a complaint; or would just like to comment on our services, please feel free to contact us. We are open to feedback and would like to hear from you.
			        </p>
			        <p style="text-align: center;"><b>Tel:</b> <span style="color: #272968;">08088883733</span></p>
			        <p style="text-align: center;"><b>Fax:</b> <span style="color: #272968;">08088883733</span></p>
			        <p style="text-align: center;"><b>Email:</b> <span style="color: #272968;">info@ecogeneral.com</span></p>
			        <ul style="text-align: center;">
			        	<li><b>Address: 45, moyosola estate</b></li>
			        </ul>
	      		</div>
			    <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        </div>
		    </div>
	  	</div>
	</div>
	<footer>
		<div class="footer">
			<div class="section_one">
				<div class="content">
					<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="aboutus.html">Aboutus</a></li>
						<li><a href="faq.html">Faqs</a></li>
						<li><a href="" data-toggle="modal" data-target="#myModal">Contactus</a></li>
						<li><a href="">Policy Privacy</a></li>
						<li><a href="">Terms and Conditions</a></li>
						<li><a href="client_zone.html">Clients Zone</a></li>
					</ul>
				</div>
			</div>
			<div class="section_two">
				<div class="footer_sub">
					<strong>Fast Loans</strong>
					<span><a href="/fast">fast loans</a></span>
					<span><a href="/payday">payday loans</a></span>
				</div>
				<div class="footer_sub">
					<strong>Cash Loans</strong>
					<span><a href="/easy">easy loans</a></span>
					<span><a href="/short">short terms loan</a></span>
				</div>
				<div class="footer_sub">
					<strong>Personal Loans</strong>
					<span><a href="/what">what is a loan</a></span>
					<span><a href="/online">online loan</a></span>
				</div>
			</div>
			<div class="section_three">
				<div class="content">
					<span>Copyright &copy; Eco General 2016, <a href="">powered by Efflux</a></span>
				</div>
			</div>
		</div>
	</footer>
</html>