<!DOCTYPE html>
<html>
	<head>
		<title>EcoGeneral Loan Services | Get Cash</title>
		<link rel="stylesheet" href="js/jquery-ui/jquery-ui.css">
		<link rel="stylesheet" href="css/bootstrap/css/bootstrap-theme.css">
		<link rel="stylesheet" href="css/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/get_cash.css">
		<link rel="stylesheet" type="text/css" href="css/font-awesome/css/font-awesome.css">
		<script src="js/modernizr.js"></script>
		<script src="static/js/angular.min.js"></script>
	</head>
	<body  ng-app="mainApp">
		<div ng-controller="ProfileController" class="main_body clearfix">
			<div class="first_section">
				<div class="header">
					<div class="header_content">	
						<div class="tabs">
							<ul>
								<li style="background-color:#15A7DF;"><a href="/">Home</a></li>
								<li><a href="/about">About</a></li>
								<li><a href="/faq">FAQ</a></li>
								<li><a href="/client">Client Zone</a></li>
							</ul>
						</div>
						<div class="social_media">
							<ul>
								<li><a href="www.facebook.com"><i class="fa fa-facebook-square font_awesome" aria-hidden="true"></i></a></li>
								<li><a href="wwww.twitter.com"><i class="fa fa-twitter-square font_awesome" aria-hidden="true"></i></a></li>
								<li><a href="www.instagram.com"><i class="fa fa-instagram font_awesome" aria-hidden="true"></i></a></li>
								<li><a href="www.youtube.com"><i class="fa fa-youtube-play font_awesome" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="logo_wrap clearfix">
					<!-- <div class="logo_div clearfix">
						<a href="" class="clearfix">
							<div class="logo"></div>
						</a>
					</div> -->
					<div class="logo_content_div">
						<h1>
			                THE ENTIRE, ONLINE APPLICATION PROCESS IS 100% SECURE FROM START TO FINISH.
						</h1>
						<span class="style">
							<p>
								Please complete the application form below.
							</p>
						</span>
					</div>
				</div>
			</div>

			<div class="second_section clearfix">
				<div class="record_wrap">
					<div class="record_button first_color">
						<div class="left">
							<p class="bold" ng-cloak>&#8358;[[borrow | number]]</p>
							<p class="small">Total Borrowing</p>
						</div>
						<div class="right">
							<i class="fa fa-shopping-cart" aria-hidden="true"></i>
						</div>
					</div>
					<div class="record_button second_color">
						<div class="left">
							<p class="bold" ng-cloak>&#8358;[[interest | number]]</p>
							<p class="small">Interest & Fees</p>
						</div>
						<div class="right">
							<i class="fa fa-server" aria-hidden="true"></i>
						</div>
					</div>
					<div class="record_button first_color">
						<div class="left">
							<p class="bold" ng-cloak>&#8358;[[total | number]]</p>
							<p class="small">Total Repayable</p>
						</div>
						<div class="right">
							<i class="fa fa-reply-all" aria-hidden="true"></i>
						</div>
					</div>
					<div class="record_button">
						<button class="second_color">
							<a href="/" aria-expanded="false" aria-controls="collapseExample">
								Adjust Fund
							</a>
						</button>
					</div>
				</div>
				<div class="collapse adjust_fund clearfix" id="collapseExample">
					<div class="well adjust_fund_content clearfix">
						<div class="left_content clearfix">
							<div class="tool">
								<div class="labe">
									How much money do you need?
								</div>
								<div class="main_tooltip">
									<table cellpadding="0" cellspacing="0">
										<tbody>
											<tr>
												<td class="minus" style="width:30px">
													<a href="" style="font-size:20px; float:left; padding-right:7px;">
														<i class="fa fa-minus-circle" aria-hidden="true"></i>
													</a>
												</td>
												<td class="slide" style="width:495px">
													<span>NGN1,000.00</span><span style="float:right;">NGN5,000.00</span>
													<div id="slider"></div>
												</td>
												<td class="plus" style="width:30px; float:right; padding-left:13px;">
													<a href="" style="font-size:20px;">
														<i class="fa fa-plus-circle" aria-hidden="true"></i>
													</a>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="right_content">
							<div class="slide_values" style="margin-top:0px;">
								<div class="main_value">
									NGN6,000:00
								</div>
								<div class="value_name">
									Total Borrowing
								</div>
							</div>
							<div class="icon">
								<i class="fa fa-cart-plus" aria-hidden="true"></i>
							</div>
						</div>

						<div class="left_content clearfix">
							<div class="tool">
								<div class="labe">
									When is your next salary date?
								</div>
								<div class="main_tooltip">
									<table cellpadding="0" cellspacing="0">
										<tbody>
											<tr>
												<td class="minus" style="width:30px">
													<a href="" style="font-size:20px; float:left; padding-right:7px;">
														<i class="fa fa-minus-circle" aria-hidden="true"></i>
													</a>
												</td>
												<td class="slide" style="width:495px">
													<span>10 days</span><span style="float:right;">40 days</span>
													<div id="slide"></div>
												</td>
												<td class="plus" style="width:30px; float:right; padding-left:13px;">
													<a href="" style="font-size:20px;">
														<i class="fa fa-plus-circle" aria-hidden="true"></i>
													</a>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="right_content">
							<div class="slide_values" style="margin-top:0px; background:#15A7DF;">
								<div class="main_value">
									NGN10,000:00
								</div>
								<div class="value_name">
									Interest And Fees
								</div>
							</div>
							<div class="icon">
								<i class="fa fa-server" aria-hidden="true"></i>
							</div>
						</div>

						<div class="left_content_noslide clearfix">
							<div class="tool">
								<div class="labe">
									You are borrowing for <span class="white">30</span> days. Your next payday is on <span class="white">Tuesday 16th August 2016</span>, which will be your repayment date for the loan.
								</div>
							</div>
						</div>
						<div class="right_content">
							<div class="slide_values" style="margin-top:0px; background:#272968;">
								<div class="main_value">
									NGN13,000:00
								</div>
								<div class="value_name">
									Total Repayable
								</div>
							</div>
							<div class="icon">
								<i class="fa fa-reply-all" aria-hidden="true"></i>
							</div>
						</div>
					</div>
				</div>
				<div class="apply_content_intro">
					<div class="apply_content">
						If you need any further assistance please call us immediately on 08080880808.
					</div>
				</div>
				<form method="post" action="/cash">
					<div class="form_content">
						<div class="form_header">
							<span class="first_color">Personal Details</span> (all <span style="color:red;">*</span> denote mandatory fields)
						</div>
						<div class="title_wrap">
							<div class="first_title">
							Title
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								Name
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								Surname
								<span style="color:red;">*</span>
							</div>
						</div>
						<div class="input_wrap">
							<div class="input_title">
								<select name="title" id="title" form="carform" required>
								  <option value="Mr." class="capitalize">Mr.</option>
								  <option value="Mrs." class="capitalize">Mrs.</option>
								  <option value="Ms." class="capitalize">Ms.</option>
								  <option value="Miss" class="capitalize">Miss</option>
								</select>
							</div>
							<div class="input_name">
								<input name="first_name" type="text" id="first_name" class="input" required>
							</div>
							<div class="input_name">
								<input name="last_name" type="text" id="last_name" class="input" required>
							</div>
						</div>

						<div class="title_wrap">
							<div class="first_title">
								Bank Verification Number
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								Gender
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								Date of Birth
								<span style="color:red;">*</span>
							</div>
						</div>
						<div class="input_wrap">
							<div class="input_title">
								<div class="">
									<input name="bvn" type="text" id="bvn" class="input" required>
								</div>
							</div>
							<div class="input_name">
								<select name="gender" form="carform" id="gender" required>
									<option value="Male" class="capitalize">Male</option>
									<option value="Female" class="capitalize">Female</option>
								</select>
							</div>
							<div class="input_name">
								<input name="date_of_birth" type="date" id="date_of_birth" class="input" required>
							</div>
						</div>
					</div>
					<hr/>
					<div class="form_content">
						<div class="form_header">
							<span class="first_color">Contact Details</span>
						</div>
						<div class="title_wrap">
							<div class="first_title">
								Street
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								City
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								State
								<span style="color:red;">*</span>
							</div>
						</div>
						<div class="input_wrap">
							<div class="input_title">
								<input name="street" type="text" id="street" class="input" required>
							</div>
							<div class="input_name">
								<input name="city" type="text" id="city" class="input" required>
							</div>
							<div class="input_name">
								<select name="state" id="state" form="carform" required>
									<option value="Abia" class="capitalize">Abia</option>
									<option value="Adamawa" class="capitalize">Adamawa</option>
									<option value="Akwa Ibom" class="capitalize">Akwa Ibom</option>
									<option value="Bauchi" class="capitalize">Bauchi</option>
									<option value="Bayelsa" class="capitalize">Bayelsa</option>
									<option value="Benue" class="capitalize">Benue</option>
									<option value="Borno" class="capitalize">Borno</option>
									<option value="Cross River" class="capitalize">Cross River</option>
									<option value="Delta" class="capitalize">Delta</option>
									<option value="Ebonyi" class="capitalize">Ebonyi</option>
									<option value="Edo" class="capitalize">Edo</option>
									<option value="Ekiti" class="capitalize">Ekiti</option>
									<option value="Enugu" class="capitalize">Enugu</option>
									<option value="FCT" class="capitalize">FCT</option>
									<option value="Gombe" class="capitalize">Gombe</option>
									<option value="Imo" class="capitalize">Imo</option>
									<option value="Jigawa" class="capitalize">Jigawa</option>
									<option value="Kaduna" class="capitalize">Kaduna</option>
									<option value="Kano" class="capitalize">Kano</option>
									<option value="Katsina" class="capitalize">Katsina</option>
									<option value="Kebbi" class="capitalize">Kebbi</option>
									<option value="Kogi" class="capitalize">Kogi</option>
									<option value="Kwara" class="capitalize">Kwara</option>
									<option value="Lagos" class="capitalize">Lagos</option>
									<option value="Nasarawa" class="capitalize">Nasarawa</option>
									<option value="Niger" class="capitalize">Niger</option>
									<option value="Ogun" class="capitalize">Ogun</option>
									<option value="Ondo" class="capitalize">Ondo</option>
									<option value="Osun" class="capitalize">Osun</option>
									<option value="Oyo" class="capitalize">Oyo</option>
									<option value="Plateau" class="capitalize">Plateau</option>
									<option value="Rivers" class="capitalize">Rivers</option>
									<option value="Sokoto" class="capitalize">Sokoto</option>
									<option value="Taraba" class="capitalize">Taraba</option>
									<option value="Yobe" class="capitalize">Yobe</option>
									<option value="Zamfara" class="capitalize">Zamfara</option>
								</select>
							</div>
						</div>
					</div>
					<hr/>
					<div class="form_content">
						<div class="form_header">
							<span class="first_color">Living Details</span>
						</div>
						<div class="title_wrap">
							<div class="first_title">
								Mobile/Cell
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								Marital Status
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								Dependants
								<span style="color:red;">*</span>
							</div>
						</div>
						<div class="input_wrap">
							<div class="input_title">
								<input name="phone" type="text" id="phone" class="input" required>
							</div>
							<div class="input_name">
								<select name="marital_status" id="marital_status" form="carform" required>
									<option value="single" class="capitalize">single</option>
									<option value="married" class="capitalize">married</option>
									<option value="divorced" class="capitalize">divorced</option>
								</select>
							</div>
							<div class="input_name">
								<input name="dependants" type="number" id="dependants" class="input" required>
							</div>
						</div>
					</div>
					<hr/>
					<div class="form_content">
						<div class="form_header">
							<span class="first_color">Create an Account</span>
						</div>
						<div class="title_wrap">
							<div class="first_title">
								Email
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								Password
								<span style="color:red;">*</span>
							</div>
							<div class="title first_title">
								Confirm Password
								<span style="color:red;">*</span>
                                <small style="color: red; font-size: 7px" ng-show="error">Passwords don't match</small>
							</div>
						</div>
						<div class="input_wrap">
							<div class="input_title">
								<input name="email" type="email" id="email" class="input" required>
							</div>
							<div class="input_name">
								<input name="password" type="password" id="password" ng-model="password" class="input" required>
							</div>
							<div class="input_name">
								<input name="verify_password" type="password" id="verify_password" ng-model="verify" ng-change="checkPassword()" class="input" required>
							</div>
						</div>
					</div>
					<hr/>
					<div class="confirmation_div clearfix">
						<div class="form_header">
							<span class="first_color">Confirmation</span>
						</div>
						<div class="confirmation_content clearfix">
	                        Please note that we only intend to use your personal details for the purpose of
	                        this application.
							<br>
							If you would like us to continue with the application, please select 'Yes, I do'	
							<br><br>
							Do you agree to our Privacy Policy and Terms and Conditions and give us permission to conduct a credit assessment?
							<div class="agree">
								<span>
									<input type="checkbox" name="terms" ng-model="confirm"> Yes, I do
								</span>
							</div>
						</div>
						<button ng-show="confirm && error == null" type="submit" style="color: white; font-size: 20px">Complete</button>
					</div>
				</form>
			</div>
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  	<div class="modal-dialog" role="document">
				    <div class="modal-content">
				        <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					        <h4 class="modal-title" id="myModalLabel" style="font-weight: 600; font-size: 20px; font-family: 'Montserrat', sans-serif; color: #272968;">Contact Us</h4>
				        </div>
				      	<div class="modal-body">
					        <p>
					        	If you need to contact us for any reason regarding your loan; want to know more about our company, products or services; have a complaint; or would just like to comment on our services, please feel free to contact us. We are open to feedback and would like to hear from you.
					        </p>
					        <p style="text-align: center;"><b>Tel:</b> <span style="color: #272968;">08088883733</span></p>
					        <p style="text-align: center;"><b>Fax:</b> <span style="color: #272968;">08088883733</span></p>
					        <p style="text-align: center;"><b>Email:</b> <span style="color: #272968;">info@ecogeneral.com</span></p>
					        <ul style="text-align: center;">
					        	<li><b>Address: 45, moyosola estate</b></li>
					        </ul>
			      		</div>
					    <div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				        </div>
				    </div>
			  	</div>
			</div>
			<footer>
				<div class="footer">
					<div class="section_one">
						<div class="content">
							<ul>
								<li><a href="index.html">Home</a></li>
								<li><a href="aboutus.html">Aboutus</a></li>
								<li><a href="faq.html">Faqs</a></li>
								<li><a href="" data-toggle="modal" data-target="#myModal">Contactus</a></li>
								<li><a href="">Policy Privacy</a></li>
								<li><a href="">Terms and Conditions</a></li>
								<li><a href="client_zone.html">Clients Zone</a></li>
							</ul>
						</div>
					</div>
					<div class="section_two">
						<div class="footer_sub">
							<strong>Fast Loans</strong>
							<span><a href="/fast">fast loans</a></span>
							<span><a href="/payday">payday loans</a></span>
						</div>
						<div class="footer_sub">
							<strong>Cash Loans</strong>
							<span><a href="/easy">easy loans</a></span>
							<span><a href="/short">short terms loan</a></span>
						</div>
						<div class="footer_sub">
							<strong>Personal Loans</strong>
							<span><a href="/what">what is a loan</a></span>
							<span><a href="/online">online loan</a></span>
						</div>
					</div>
					<div class="section_three">
						<div class="content">
							<span>Copyright &copy; Eco General 2016, <a href="">powered by Efflux</a></span>
						</div>
					</div>
				</div>
			</footer>
		</div>

		<script src="js/jquery.js"></script>
		<script src="css/bootstrap/js/bootstrap.min.js"></script>
		<script src="js/jquery-ui/jquery-ui.js"></script>
        <script type="text/javascript" src ="static/js/app.js"></script>
	</body>

	<script>
	  $( function() {
	    	$( "#slider" ).slider();
	  	});

	  $( function() {
	    	$( "#slide" ).slider();
	  	});
  	</script>
</html>