<!DOCTYPE html>
<html>
	<head>
		<title>EcoGeneral Loan Services | Home</title>
        <link rel="stylesheet" href="static/js/jquery-ui/jquery-ui.css">
        <link rel="stylesheet" href="static/css/bootstrap/css/bootstrap-theme.css">
        <link rel="stylesheet" href="static/css/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="static/css/index.css">
        <link rel="stylesheet" type="text/css" href="static/css/font-awesome/css/font-awesome.css">
        <script src="static/js/modernizr.js"></script>
        <script src="static/js/angular.min.js"></script>
	</head>
	<body ng-app="mainApp">
	<div ng-controller="CalculateController" class="main_body clearfix" ng-init="init()">
		<div class="first_section">
			<div class="header">
				<div class="header_content">
					<div class="tabs">
						<ul>
							<li style="background-color:#15A7DF;"><a href="/">Home</a></li>
							<li><a href="/about">About</a></li>
							<li><a href="/faq">FAQ</a></li>
							<li><a href="/client">Client Zone</a></li>
						</ul>
					</div>
					<div class="social_media">
						<ul>
                            <li><a href="http://facebook.com"><i class="fa fa-facebook-square font_awesome" aria-hidden="true"></i></a></li>
                            <li><a href="http://twitter.com"><i class="fa fa-twitter-square font_awesome" aria-hidden="true"></i></a></li>
                            <li><a href="http://instagram.com"><i class="fa fa-instagram font_awesome" aria-hidden="true"></i></a></li>
                            <li><a href="http://youtube.com"><i class="fa fa-youtube-play font_awesome" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="logo_wrap clearfix">
				<div class="logo_div clearfix">
					<a href="" class="clearfix">
						<div class="logo"></div>
					</a>
				</div>
				<div class="logo_content_div">
					<h1>
		                NIGERIA'S LEADING NAME IN ONLINE, PAYDAY LOANS. FOR FAST, PAPERLESS CASH
		                LOANS UNTIL PAYDAY!
					</h1>
					<span class="style">
						You can apply from <span class="white">NGN1000</span> up to <span class="white">NGN3000</span> <br> <span style="font-size:20px; color:#fff;">SAME DAY. PAY DAY. EVERYDAY.</span>
					</span>
				</div>
			</div>
		</div>
		<div class="second_section clearfix">
			<div class="left_content clearfix">
				<div class="tool">
					<div class="labe">
						How much money do you need?
					</div>
					<div class="main_tooltip">
						<form>
							<table cellpadding="0" cellspacing="0">
								<tbody>
									<tr>
										<td class="minus" style="width:30px">
											<a href="" style="font-size:20px; float:left; padding-right:7px;">
												<i class="fa fa-minus-circle" aria-hidden="true"></i>
											</a>
										</td>
										<td class="slide" style="width:495px">
											<span>NGN[[min | number]]</span><span ng-cloak style="float:right;">NGN[[max | number]] </span>
											<input type="range" min="[[min]]" max="[[max]]" value="[[borrow]]" ng-model="borrow" ng-change="valueChanges()">
										</td>
										<td class="plus" style="width:30px; float:right; padding-left:13px;">
											<a href="" style="font-size:20px;">
												<i class="fa fa-plus-circle" aria-hidden="true"></i>
											</a>
										</td>
									</tr>
								</tbody>
							</table>
						</form>
					</div>
				</div>
			</div>
			<div class="right_content">
				<div class="slide_values" style="margin-top:0px;">
					<div class="main_value" ng-cloak>
						NGN[[borrow | number]]
					</div>
					<div class="value_name">
						Total Borrowing
					</div>
				</div>
				<div class="icon">
					<i class="fa fa-cart-plus" aria-hidden="true"></i>
				</div>
			</div>

			<div class="left_content clearfix">
				<div class="tool">
					<div class="labe">
						When is your next salary date?
					</div>
					<div class="main_tooltip">
						<table cellpadding="0" cellspacing="0">
							<tbody>
								<tr>
									<td class="minus" style="width:30px">
										<a href="" style="font-size:20px; float:left; padding-right:7px;">
											<i class="fa fa-minus-circle" aria-hidden="true"></i>
										</a>
									</td>
									<td class="slide" style="width:495px">
                                        <span>[[start | number]] days</span><span style="float:right;" ng-cloak>[[end | number]] days</span>
                                        <input type="range" min="[[start]]" max="[[end]]" value="[[date_value]]" ng-model="date_value" ng-change="dateChange()">
									</td>
									<td class="plus" style="width:30px; float:right; padding-left:13px;">
										<a href="" style="font-size:20px;">
											<i class="fa fa-plus-circle" aria-hidden="true"></i>
										</a>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="right_content">
				<div class="slide_values" style="margin-top:0px; background:#15A7DF;">
					<div class="main_value" ng-cloak>
						NGN[[interest | number]]
					</div>
					<div class="value_name">
						Interest And Fees
					</div>
				</div>
				<div class="icon">
					<i class="fa fa-server" aria-hidden="true"></i>
				</div>
			</div>

			<div class="left_content_noslide clearfix">
				<div class="tool">
					<div class="labe">
						You are borrowing for <span class="white">[[date_value]]</span> days. Your next payday is on <span class="white">[[_date | date:'fullDate']]</span>, which will be your repayment date for the loan.
					</div>
				</div>
			</div>
			<div class="right_content">
				<div class="slide_values" style="margin-top:0px; background:#272968;">
					<div class="main_value" ng-cloak>
						NGN[[total | number]]
					</div>
					<div class="value_name">
						Total Repayable
					</div>
				</div>
				<div class="icon">
					<i class="fa fa-reply-all" aria-hidden="true"></i>
				</div>
			</div>

			<div class="left_content_noslide clearfix">
				<div class="tool">
					<div class="labe">
						<div class="percentage">100%</div>
						<div class="words">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</div>
					</div>
				</div>
			</div>
			<div class="right_content">
				<div class="slide_values" style="margin-top:0px; background:#fff;">
					<div ng-click="submit()" class="img_div"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  	<div class="modal-dialog" role="document">
		    <div class="modal-content">
		        <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel" style="font-weight: 600; font-size: 20px; font-family: 'Montserrat', sans-serif; color: #272968;">Contact Us</h4>
		        </div>
		      	<div class="modal-body">
			        <p>
			        	If you need to contact us for any reason regarding your loan; want to know more about our company, products or services; have a complaint; or would just like to comment on our services, please feel free to contact us. We are open to feedback and would like to hear from you.
			        </p>
			        <p style="text-align: center;"><b>Tel:</b> <span style="color: #272968;">08088883733</span></p>
			        <p style="text-align: center;"><b>Fax:</b> <span style="color: #272968;">08088883733</span></p>
			        <p style="text-align: center;"><b>Email:</b> <span style="color: #272968;">info@ecogeneral.com</span></p>
			        <ul style="text-align: center;">
			        	<li><b>Address: 45, moyosola estate</b></li>
			        </ul>
	      		</div>
			    <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        </div>
		    </div>
	  	</div>
	</div>
	<footer>
		<div class="footer">
			<div class="section_one">
				<div class="content">
					<ul>
						<li><a href="/">Home</a></li>
						<li><a href="/about">Aboutus</a></li>
						<li><a href="/faq">Faqs</a></li>
						<li><a href="" data-toggle="modal" data-target="#myModal">Contactus</a></li>
						<li><a href="">Policy Privacy</a></li>
						<li><a href="">Terms and Conditions</a></li>
						<li><a href="/client">Clients Zone</a></li>
					</ul>
				</div>
			</div>
			<div class="section_two">
				<div class="footer_sub">
					<strong>Fast Loans</strong>
					<span><a href="/fast">fast loans</a></span>
					<span><a href="/payday">payday loans</a></span>
				</div>
				<div class="footer_sub">
					<strong>Cash Loans</strong>
					<span><a href="/easy">easy loans</a></span>
					<span><a href="/short">short terms loan</a></span>
				</div>
				<div class="footer_sub">
					<strong>Personal Loans</strong>
					<span><a href="/what">what is a loan</a></span>
					<span><a href="/online_loan">online loan</a></span>
				</div>
			</div>
			<div class="section_three">
				<div class="content">
					<span>Copyright &copy; Eco General 2016, <a href="http://www.effluxcompany.com/" target="_blank">powered by Efflux</a></span>
				</div>
			</div>
		</div>
	</footer>

	<script src="static/js/jquery.js"></script>
  	<script src="static/js/jquery-ui/jquery-ui.js"></script>
	<script src="static/css/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src ="static/js/app.js"></script>
</body>

<script>
  $( function() {
    	$( "#slider" ).slider();
  	});

  $( function() {
    	$( "#slide" ).slider();
  	});
  </script>
</html>