<!DOCTYPE html>
<html>
	<head>
		<title>Payday Loans</title>
		<link rel="stylesheet" href="js/jquery-ui/jquery-ui.css">
		<link rel="stylesheet" href="css/bootstrap/css/bootstrap-theme.css">
		<link rel="stylesheet" href="css/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/payday_loan.css">
		<link rel="stylesheet" type="text/css" href="css/font-awesome/css/font-awesome.css">
		<link rel="stylesheet" href="css/reset.css"> <!-- CSS reset -->
		<link rel="stylesheet" href="css/style.css"> <!-- Resource style -->
		<link rel="stylesheet" type="text/css" href="css/animate.css">
		<script src="js/modernizr.js"></script>
	</head>
	<body>
		<div class="first_section">
			<div class="header">
				<div class="header_content">
					<div class="tabs">
						<ul>
							<li style="background-color:#15A7DF;"><a href="/">Home</a></li>
							<li><a href="/about">About</a></li>
							<li><a href="/faq">FAQ</a></li>
							<li><a href="/client">Client Zone</a></li>
						</ul>
					</div>
					<div class="social_media">
						<ul>
							<li><a href="www.facebook.com"><i class="fa fa-facebook-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="wwww.twitter.com"><i class="fa fa-twitter-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="www.instagram.com"><i class="fa fa-instagram font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="www.youtube.com"><i class="fa fa-youtube-play font_awesome" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="logo_wrap class="clearfix">
				<div class="logo_div class="clearfix">
					<a href="" class="clearfix">
						<div class="logo"></div>
					</a>
				</div>
				<div class="logo_content_div">
					<h1>
		                NIGERIA'S LEADING NAME IN ONLINE, PAYDAY LOANS. FOR FAST, PAPERLESS CASH
		                LOANS UNTIL PAYDAY!
					</h1>
					<span class="style">
						You can apply from <span class="white">NGN1000</span> up to <span class="white">NGN3000</span> <br> <span style="font-size:20px; color:#fff;">SAME DAY. PAY DAY. EVERYDAY.</span>
					</span>
				</div>
			</div>
		</div>
		<div class="second_section clearfix">
			<h1>Payday Loans</h1>
			<em>
				Author: <b>Panama Palane</b> <br>
				Date: June 6, 2016
			</em>
			<br>
			<br>
			<h2>
				Is a payday loan right for you?
			</h2>
			<p>
				You cannot predict the status of your financial survival month after month. Even with a monthly salary, unexpected expenses pop up. So what do you do when, after your salary, you've paid all your accounts, bond/rent and bought all your groceries, and basically followed through on your budget down to the T. But, then suddenly, you find yourself faced with a family emergency that requires your immediate financial attention? <br><br> 

				Applying for a loan crosses your mind, but then you realise that it may take a while before it's approved, and you need the loan immediately. Consider a payday loan! But, what is a payday loan? Well, if you don't know about it you're in the minority, because hundreds of South Africans are now using payday loans. A payday loan is a short-term loan that's usually due the next time you get paid. A lender charges a fee in exchange for lending you money until your next payday, hence it's called a payday loan. You're borrowing just enough to get through to your next payday, upon which the money is due. <br><br>

				How do you get it? As long as you are employed and have a bank account, it's simple. With economic conditions the way they have been over past years, people have resorted to instant approval payday loan lenders more than ever, and have become more open about doing so because payday loans are fast and easy. Online payday loans with instant approval are relatively small. It's not a long-term measure because it should be paid back whenever your next paycheck arrives. For some people this date can be less than a month, though the loan can last longer if you're paid monthly. <br> <br>

				Like traditional loans, payday loans come with an interest rate percentage, and, as it stands, South Africa's payday loan rate, compared to other countries, is very low and far more regulated. Lets look at South Africa vs. the UK for instance. In South Africa, legislature dictates that payday lenders only charge a maximum interest rate of 5% p/m, whereas in the UK (and others like it) they may charge up to 200% interest. This only goes to show that payday lending — or any short-term finance for that matter is definitely the future of the microfinance industry in South Africa. <br><br>

				So, is a payday loan a wise route to take? If you're looking for a short-term quick loan and you're able to pay it back when your next salary arrives, then definitely! It’'' loans, a payday loan is a more affordable option to go for. And where's the best place for you to get a payday loan? Look no further, EcoGeneral is here for that sole purpose. Because there's a growing number of South Africans struggling to access short-term credit, we've made it our mission to create a solution that will lift the burden of denial-of-credit for the little things small loans over short periods. We offer payday loans with minimal interest rates and maximum convenience. You apply, we deposit your money, and you repay us when you next get paid. Simple. <br><br>

				EcoGeneral fast, paperless cash loans untill payday.
			</p>
		</div>
	</body>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  	<div class="modal-dialog" role="document">
		    <div class="modal-content">
		        <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel" style="font-weight: 600; font-size: 20px; font-family: 'Montserrat', sans-serif; color: #272968;">Contact Us</h4>
		        </div>
		      	<div class="modal-body">
			        <p>
			        	If you need to contact us for any reason regarding your loan; want to know more about our company, products or services; have a complaint; or would just like to comment on our services, please feel free to contact us. We are open to feedback and would like to hear from you.
			        </p>
			        <p style="text-align: center;"><b>Tel:</b> <span style="color: #272968;">08088883733</span></p>
			        <p style="text-align: center;"><b>Fax:</b> <span style="color: #272968;">08088883733</span></p>
			        <p style="text-align: center;"><b>Email:</b> <span style="color: #272968;">info@ecogeneral.com</span></p>
			        <ul style="text-align: center;">
			        	<li><b>Address: 45, moyosola estate</b></li>
			        </ul>
	      		</div>
			    <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        </div>
		    </div>
	  	</div>
	</div>
	<footer>
		<div class="footer">
			<div class="section_one">
				<div class="content">
					<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="aboutus.html">Aboutus</a></li>
						<li><a href="faq.html">Faqs</a></li>
						<li><a href="" data-toggle="modal" data-target="#myModal">Contactus</a></li>
						<li><a href="">Policy Privacy</a></li>
						<li><a href="">Terms and Conditions</a></li>
						<li><a href="client_zone.html">Clients Zone</a></li>
					</ul>
				</div>
			</div>
			<div class="section_two">
				<div class="footer_sub">
					<strong>Fast Loans</strong>
					<span><a href="/fast">fast loans</a></span>
					<span><a href="/payday">payday loans</a></span>
				</div>
				<div class="footer_sub">
					<strong>Cash Loans</strong>
					<span><a href="/easy">easy loans</a></span>
					<span><a href="/short">short terms loan</a></span>
				</div>
				<div class="footer_sub">
					<strong>Personal Loans</strong>
					<span><a href="/what">what is a loan</a></span>
					<span><a href="/online">online loan</a></span>
				</div>
			</div>
			<div class="section_three">
				<div class="content">
					<span>Copyright &copy; Eco General 2016, <a href="">powered by Efflux</a></span>
				</div>
			</div>
		</div>
	</footer>
</html>