<!DOCTYPE html>
<html>
	<head>
		<title>Short-term Loans</title>
		<link rel="stylesheet" href="js/jquery-ui/jquery-ui.css">
		<link rel="stylesheet" href="css/bootstrap/css/bootstrap-theme.css">
		<link rel="stylesheet" href="css/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/short_loan.css">
		<link rel="stylesheet" type="text/css" href="css/font-awesome/css/font-awesome.css">
		<link rel="stylesheet" href="css/reset.css"> <!-- CSS reset -->
		<link rel="stylesheet" href="css/style.css"> <!-- Resource style -->
		<link rel="stylesheet" type="text/css" href="css/animate.css">
		<script src="js/modernizr.js"></script>
	</head>
	<body>
		<div class="first_section">
			<div class="header">
				<div class="header_content">
					<div class="tabs">
						<ul>
							<li style="background-color:#15A7DF;"><a href="/">Home</a></li>
							<li><a href="/about">About</a></li>
							<li><a href="/faq">FAQ</a></li>
							<li><a href="/client">Client Zone</a></li>
						</ul>
					</div>
					<div class="social_media">
						<ul>
							<li><a href="www.facebook.com"><i class="fa fa-facebook-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="wwww.twitter.com"><i class="fa fa-twitter-square font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="www.instagram.com"><i class="fa fa-instagram font_awesome" aria-hidden="true"></i></a></li>
							<li><a href="www.youtube.com"><i class="fa fa-youtube-play font_awesome" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="logo_wrap class="clearfix">
				<div class="logo_div class="clearfix">
					<a href="" class="clearfix">
						<div class="logo"></div>
					</a>
				</div>
				<div class="logo_content_div">
					<h1>
		                NIGERIA'S LEADING NAME IN ONLINE, PAYDAY LOANS. FOR FAST, PAPERLESS CASH
		                LOANS UNTIL PAYDAY!
					</h1>
					<span class="style">
						You can apply from <span class="white">NGN1000</span> up to <span class="white">NGN3000</span> <br> <span style="font-size:20px; color:#fff;">SAME DAY. PAY DAY. EVERYDAY.</span>
					</span>
				</div>
			</div>
		</div>
		<div class="second_section clearfix">
			<h1>Short-term Loans</h1>
			<em>
				Author: <b>Panama Palane</b> <br>
				Date: June 6, 2016
			</em>
			<br>
			<br>
			<h2>
				Short-term loans payday lending?
			</h2>
			<p>
				Face it, sometimes we all need a short-term loan to help us with our short-term financial needs, like car repairs, family vacations or an unexpected emergency that may pop up. <br><br> 

				Here's a scenario: you work an eight to five job every day of the week and get a salary every month that enables you to cover your important expenses, like paying your rent/bond, paying your bills, and purchasing your groceries, etc. But what happens when you need cash mid-month? After having done everything you needed to do with your salary, a short-term loan is the best and wisest route to take when faced with an emergency. <br><br>

				A payday loan is a great type of short-term loan and there are hundreds of financial lenders willing and happy to offer short-term loans. That's great, but every lender has different criteria for taking out a loan some of which may land you in more trouble than you were before taking out the short-term loan. <br> <br>

				With so many financial organisations offering short-term loans, or any kind of loan for that matter, you're faced with the dilemma of figuring out which one is right for you: which loan will suit your financial state and lifestyle. <br><br>

				It's important to know beforehand that short-term loan providers have set a few criteria for an applicant to qualify for a payday loan. You need to be a citizen of South Africa and older than 18. You must be employed and earn a regular salary and hold a valid bank account. <br><br>

				For a short-term loan with EcoGeneral, you need a valid Nigeria ID, a valid and operational bank account and to be employed and earn a regular salary. With EcoGeneral payday lending operates on a 40-day cycle which means that you can repay your loan when you next get paid. <br><br>

				We are committed to responsible lending and advise you to only borrow as much as you can afford to pay back. <br><br>

				Apply for your shot-term loan with EcoGeneral for peace of mind. We ensure that you are paid on time, every time.
			</p>
		</div>
	</body>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  	<div class="modal-dialog" role="document">
		    <div class="modal-content">
		        <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel" style="font-weight: 600; font-size: 20px; font-family: 'Montserrat', sans-serif; color: #272968;">Contact Us</h4>
		        </div>
		      	<div class="modal-body">
			        <p>
			        	If you need to contact us for any reason regarding your loan; want to know more about our company, products or services; have a complaint; or would just like to comment on our services, please feel free to contact us. We are open to feedback and would like to hear from you.
			        </p>
			        <p style="text-align: center;"><b>Tel:</b> <span style="color: #272968;">08088883733</span></p>
			        <p style="text-align: center;"><b>Fax:</b> <span style="color: #272968;">08088883733</span></p>
			        <p style="text-align: center;"><b>Email:</b> <span style="color: #272968;">info@ecogeneral.com</span></p>
			        <ul style="text-align: center;">
			        	<li><b>Address: 45, moyosola estate</b></li>
			        </ul>
	      		</div>
			    <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        </div>
		    </div>
	  	</div>
	</div>
	<footer>
				<div class="footer">
					<div class="section_one">
						<div class="content">
							<ul>
								<li><a href="index.html">Home</a></li>
								<li><a href="aboutus.html">Aboutus</a></li>
								<li><a href="faq.html">Faqs</a></li>
								<li><a href="" data-toggle="modal" data-target="#myModal">Contactus</a></li>
								<li><a href="">Policy Privacy</a></li>
								<li><a href="">Terms and Conditions</a></li>
								<li><a href="client_zone.html">Clients Zone</a></li>
							</ul>
						</div>
					</div>
					<div class="section_two">
						<div class="footer_sub">
							<strong>Fast Loans</strong>
							<span><a href="/fast">fast loans</a></span>
							<span><a href="/payday">payday loans</a></span>
						</div>
						<div class="footer_sub">
							<strong>Cash Loans</strong>
							<span><a href="/easy">easy loans</a></span>
							<span><a href="/short">short terms loan</a></span>
						</div>
						<div class="footer_sub">
							<strong>Personal Loans</strong>
							<span><a href="/what">what is a loan</a></span>
							<span><a href="/online">online loan</a></span>
						</div>
					</div>
					<div class="section_three">
						<div class="content">
							<span>Copyright &copy; Eco General 2016, <a href="">powered by Efflux</a></span>
						</div>
					</div>
				</div>
			</footer>
</html>